IMPORT-MODULE SMLETS

$SIZE1 = “$INSTANCESIZE”
$SIZE2 = $SIZE1 -REPLACE “{“, “”
$SIZE3 = $SIZE2 -REPLACE “}”, “”
$SIZE4 = GET-SCSMENUMERATION -ID $SIZE3
$SIZENAME = $SIZE4.DISPLAYNAME

START-SMARUNBOOK -WEBSERVICEENDPOINT HTTPS://WAP01 `
-NAME “SCSM__DEPLOY_NEW_VM” -PARAMETERS `
@{“INSTANCESIZE”=”$SIZENAME”; ` “VMNAME”=”$VMNAME”;”ACTIVITYID”=”$ACTIVITYID”} 
